apm install language-babel
apm install language-postcss
apm install autocomplete-modules
apm install autocomplete-paths
apm install atom-ternjs
apm install emmet
apm install linter
apm install linter-jshint
apm install linter-eslint
apm install editorconfig
apm install git-plus
apm install merge-conflicts
apm install project-manager
apm install minimap
apm install minimap-git-diff
apm install file-icons
apm install atom-beautify
apm install pigments
apm install color-picker
apm install highlight-selected
apm install minimap-highlight-selected
apm install docblockr
apm install markdown-preview-plus
apm install hyperclick
apm install js-hyperclick
apm install travis-ci-status
apm install platformio-ide-terminal
apm install sync-settings
